### ISSUE TITLE
Missing source and issues links on the CurseForge page and other stuff

### ISSUE THREAD

**Issue by K0-RR** [JamCoreModding/Notify#1]
The only way to access your GitHub is by looking for a link inside fabric.mod.json.

Also, the homepage https://github.com/JamCoreModding/Notify/blob/main/src/main/resources/fabric.mod.json#L12 link just opens the main MC mods CF page.

And the last thing, could you update your Gradle to 7.3 to enable building with Java 17? https://github.com/JamCoreModding/Notify/blob/main/gradle/wrapper/gradle-wrapper.properties#L3

**Comment by Jamalam360** [comment]
Thanks, I forgot to update all of those. Why do you want to build with Java 17, just out of interest?

**Comment by Jamalam360** [comment]
Fixed everything in Version `1.0.1`

**Comment by K0-RR** [comment]
> Why do you want to build with Java 17, just out of interest?

I'm one of those weird guys who always use the bleeding edge just to have more problems

**Comment by Jamalam360** [comment]
You were the person that was making that modpack right? I think you've opened an issue on another one of my projects before
