### ISSUE TITLE
Crashes when opening ModMenu

### ISSUE THREAD

**Issue by Nincodedo** [JamCoreModding/Notify#16]
Mods installed:
- Cloth Config 6.0.43
- ModMenu 3.0.0
- Notify 1.3.0-rc1

[crash-2021-12-05_03.30.04-client.txt](https://github.com/JamCoreModding/Notify/files/7655584/crash-2021-12-05_03.30.04-client.txt)

**Comment by Jamalam360** [comment]
I'll get this fixed ASAP, thanks

**Comment by Jamalam360** [comment]
Will be released in the next 10 minutes
