### ISSUE TITLE
Crash on launch. Incompatibility with Flour's Various Tweaks (FVT) mod

### ISSUE THREAD

**Issue by TalEdd** [JamCoreModding/Notify#17]
[crash-2021-12-08_14.23.37-client.txt](https://github.com/JamCoreModding/Notify/files/7673857/crash-2021-12-08_14.23.37-client.txt)
[crash-2021-12-08_14.23.36-server.txt](https://github.com/JamCoreModding/Notify/files/7673858/crash-2021-12-08_14.23.36-server.txt)

**Comment by Jamalam360** [comment]
Doesn't seem like an issue with notify from a first look. Does it still happen if you remove the mod

**Comment by TalEdd** [comment]
Yup, removing it from load order makes it stop crashing.

**Comment by Jamalam360** [comment]
Alright I'll take a look later

**Comment by Jamalam360** [comment]
Have you checked whether this still occurs recently? I've made a lot of changes so it might have been fixed.

**Comment by Jamalam360** [comment]
I'll be working on this for the release of V2.0.0 soon
