### ISSUE TITLE
Crash after installation

### ISSUE THREAD

**Issue by ghost** [JamCoreModding/Notify#2]
## Expected Behavior
For the game to start as normal

## Current Behavior
When the mod is enabled, the game crashes

## Steps to Reproduce
1. Download v1.0.1 from [CurseForge](https://www.curseforge.com/minecraft/mc-mods/notify/files)
2. Place the .jar into `C:\Users\Nikolai\AppData\Roaming\gdlauncher_next\instances\Minecraft (Fabric)\mods`
3. Start the instance from GDLauncher

## Crash logs
https://pastebin.com/Mcwc5hER

**Comment by Jamalam360** [comment]
I don't think this is an issue with Notify, the logs are about block models or something completely not relevant to notify. I think another one of your mods is causing the issue

**Comment by ghost** [comment]
Considering the issue stops after I turn your mod off, I don't think that's
the case.

**Comment by Jamalam360** [comment]
The logs are completely unrelated. Either you sent the wrong logs or it's not to do with Notify.
