### ISSUE TITLE
[BUG] Mixin crash on opening ModMenu

### ISSUE THREAD

**Issue by srnyx** [JamCoreModding/Notify#5]
Fabric 1.17.1
Removing mod fixes it

https://paste.srnyx.xyz/etovililix.yaml

**Comment by Jamalam360** [comment]
Weird, the log mentions an Iris method returning null, which is completely unrelated to any code that this mod touches. I'll look into this

**Comment by Jamalam360** [comment]
We've had a discussion about this, it's definitely an issue with Iris not being initialised but I don't see why that's causing it to break with my mod. I'll try check at some point

**Comment by shaksternano** [comment]
Game crashes on startup with only Notify and Fabric API installed
https://pastebin.com/fZedfZGL

**Comment by Jamalam360** [comment]
You need Cloth Config as a dependency, I'll add it in the fabric.mod.json so that's more obvious

**Comment by shaksternano** [comment]
Still crashes on startup even with cloth config installed
https://pastebin.com/GvUhyMCY

**Comment by Jamalam360** [comment]
You also need mod menu, thought that would be a given considering the mods entire purpose is to add a badge to mod menu

**Comment by shaksternano** [comment]
Game launches with mod menu installed but crashes when the mods button in the main menu is pressed:
https://pastebin.com/WiU44KwR

Additionally it goes back to crashing on startup when I add my mod which I've added support for notify for using the gradle.properties way:
https://pastebin.com/6RHyyZEJ
https://github.com/ShakterNano/WMITEF/blob/6f3cd05e251db86e3d6530fe16b7dd6756473449/src/main/resources/fabric.mod.json#L31-L32

If I revert back to the version of my mod without support for notify it works the same way as the first crash in this comment, it crashes when the mods button is pressed
https://pastebin.com/f2mqPLgR

Game works fine when Notify is removed.

**Comment by Jamalam360** [comment]
@srnyx , further discussion of your issue can go in #6 for now as that's the general thread for iris incompatibility. This issue is now related to the mixin errors above

**Comment by Jamalam360** [comment]
OK, the Mixin crash should be fixed with the latest version (1.1.1), sorry about that @ShakterNano

**Comment by shaksternano** [comment]
It would be great if you made Fabric API, Cloth config and mod menu required dependancies on curseforge as well as in fabric.mod.json

**Comment by Jamalam360** [comment]
👍 will do, Fabric API is no longer a required dependency by the way
